[33mWARNING [0m selenium.webdriver.common.selenium_manager:selenium_manager.py:149 There was an error managing chromedriver (error sending request for url (https://googlechromelabs.github.io/chrome-for-testing/known-good-versions-with-downloads.json): error trying to connect: dns error: No such host is known. (os error 11001)); using driver found in the cache
[33mWARNING [0m selenium.webdriver.common.selenium_manager:selenium_manager.py:149 Error sending stats to Plausible: error sending request for url (https://plausible.io/api/event): error trying to connect: dns error: No such host is known. (os error 11001)